FROM ros:kinetic-robot

RUN apt-get update && \
    yes | apt-get install ros-kinetic-ros-tutorials ros-kinetic-rqt-graph vim ros-kinetic-turtlebot3 ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control